# Generated by Django 5.1.3 on 2024-11-24 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "bookId",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("rating", models.FloatField()),
                ("description", models.TextField()),
                ("pages", models.IntegerField()),
                ("coverImg", models.URLField()),
            ],
            options={
                "db_table": "books_info",
            },
        ),
    ]
