# Generated by Django 5.1.3 on 2024-11-24 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table="books_info",
        ),
    ]
